base_url = "https://serene-demo.pages.dev"
title = "Home"
description = "The demo site of zola theme serene"
default_language = "en"
theme = "serene"
output_dir = "public"
compile_sass = true
minify_html = false
build_search_index = false
generate_feeds = false
feed_filenames = ["feed.xml"]
taxonomies = [{ name = "tags" }, { name = "categories" }]

[markdown]
highlight_code = true
highlight_theme = "css"
extra_syntaxes_and_themes = ["themes/serene/highlight_themes"]
highlight_themes_css = [
  { theme = "serene-light", filename = "hl-light.css" },
  { theme = "serene-dark", filename = "hl-dark.css" },
]
render_emoji = false
external_links_target_blank = true
external_links_no_follow = true
external_links_no_referrer = true
smart_punctuation = false

[slugify]
paths = "on"
taxonomies = "on"
anchors = "on"

#=========================================================================================

[extra]

sections = [
  { name = "posts", path = "/posts", is_external = false },
  # { name = "tags", path = "/tags", is_external = false },
  # { name = "collections", path = "/collections", is_external = false },
  { name = "about", path = "/about", is_external = false },
]
blog_section_path = "/posts"

force_theme = false
back_link_text = "Back"

footer_copyright = "© 2025 Jian De"
footer_credits = true

not_found_error_text = "404 Not Found"
not_found_recover_text = "« back to home »"

reaction = false
reaction_align = "right"
reaction_endpoint = "https://reaction-serene-demo.isunjn.workers.dev"